"""Verbatim static prose sections of the committed lambda fullcircuit models,
carried by build_fullcircuit.py. These are model DATA (header, fixed Table-3
parameters, R1-R5 turnover reactions, growth/dilution rules) -- the structured
parts (RNAP molecule type, O_R/P_RE/P_L functions, elongation rules) are generated
by plus_gen/or_system/pre_pl and spliced in by build_fullcircuit.py."""
# ruff: noqa: E501  (verbatim model prose; some header/parameter lines exceed 100 cols)

BASE = {'header': ['# lambda_switch_arkin1998_fullcircuit.bngl',
            '#',
            '# FULL lysis/lysogeny decision circuit of bacteriophage lambda, after',
            '#   Arkin, Ross & McAdams (1998), Genetics 149:1633-1648.',
            '#',
            '# This is the complete closed-loop, NETWORK-FREE reconstruction (run with NFsim or',
            '# RuleMonkey), the genetic-circuit companion to the curated non-genetic network in',
            '# lambda_switch_arkin1998.bngl (Table 3, R1-R5) and the Shea-Ackers promoter',
            '# activation in lambda_switch_arkin1998_promoters.bngl (Table 1). It couples:',
            '#',
            '#   TRANSCRIPTION (four operons P_R, P_L, P_RM, P_RE) as a state-increment ("~PLUS")',
            '#     RNAP-position model: one generic stepping rule per operon advances loc~? by one',
            '#     nt-equivalent; N-antitermination at nutR/nutL (unimolecular functional rate',
            '#     k_anti*N) and terminator fall-off at tR1 (~50%) / tL1 (~80%) compete with the',
            '#     step; gene stops emit mRNA. Initiation propensities are the Shea-Ackers open-',
            '#     complex rates A_PR()/A_PRM() (40-config O_R partition function, Table 1/2) and',
            '#     A_PRE()/A_PL() (Table 1), evaluated live from the current repressor levels.',
            '#   TRANSLATION as a geometric-burst competition per transcript (mean 10 proteins,',
            '#     Arkin Table 2 / assumption 8): mRNA_X -> mRNA_X + X at k_tl=2.0/s vs',
            '#     mRNA_X -> 0 at k_rnase=0.2/s.',
            '#   PROTEIN TURNOVER R1-R5 (Table 3): CI/Cro dimerization+degradation, N decay, and',
            '#     CII/CIII competitive proteolysis by two host proteases (P1=35, P2=140 nM) with',
            '#     CIII protection of CII -- verbatim from lambda_switch_arkin1998.bngl.',
            '#',
            '# The four promoters are read from the LIVE proteins the circuit produces, closing '
            'the',
            '# feedback loop: A_PR/A_PRM/A_PL <- CI2 & Cro2 dimers; A_PRE <- free CII; antiterm <- '
            'N.',
            '#',
            '# MOI (multiplicity of infection = phage genome copies) is the parameter MOI (default',
            '# 6, the Arkin Fig 3-5 value). Initiation is catalytic on a shared genome species',
            '# DNA() seeded at MOI: DNA() -> DNA() + RNAP(...) A_X(), so total initiation for',
            '# operon X is A_X()*MOI (each genome copy equilibrates with the shared free-repressor',
            '# / free-RNAP pools -- standard Shea-Ackers). MOI=1 reduces to a single genome.',
            '# Free RNAP (30 nM), ribosomes, and proteases are constant buffered pools (Arkin',
            '# modeling assumptions 3 & 6). Cell growth/dilution is not modeled (constant volume;',
            '# 1 molecule ~ 1 nM at V_ref=1.66054e-15 L, so molecule counts read as nM).',
            '#',
            '# NETWORK-FREE ENGINE NOTE (important): the promoter functional rates are driven by',
            '# MOLECULES-type observables of the dimers -- Obs_CI2/Obs_Cro2 = Molecules',
            '# CI(d!1).CI(d!1) / Cro(d!1).Cro(d!1) = 2x the dimer COUNT -- with dimer_scale=0.5 in',
            '# the partition functions to recover the dimer concentration. NFsim silently FREEZES '
            'a',
            '# functional rate that depends on a SPECIES-type observable (it refreshes such rates',
            '# only at output times, not on reaction events; RuleWorld/nfsim#86), so the live',
            '# repressor feedback MUST be read from Molecules obs. The Species readouts CI2_dimer '
            '/',
            '# Cro2_dimer are for plotting (clean dimer count) and to keep NFsim complex '
            'bookkeeping',
            '# (-cb) enabled; they never drive a rate.',
            '#',
            '# Lysogeny classifier (Arkin footnote 12, p.1639-1640): a cell is committed to '
            'lysogeny',
            '# when free-CII production activated P_RE and [CI2] > [Cro2] at the end of the 35-min',
            '# cell cycle. Run with the companion driver run_fullcircuit.py.',
            '#',
            '# Actions: writeXML only -- this is a network-free model. Generate XML with',
            '#   `bionetgen run -i lambda_switch_arkin1998_fullcircuit.bngl`',
            '# then simulate the XML with NFsim (needs -cb) or RuleMonkey; run_fullcircuit.py does',
            '# this via bngsim and reproduces Arkin Figs 3 and 6.',
            '#',
            '# Generated from models/lambda_switch_arkin1998/generator/ (plus_gen.py ~PLUS generator +',
            '# or_system.py / pre_pl.py Shea-Ackers rates + build_fullcircuit.py assembly).',
            ''],
 'params': ['begin parameters',
            '  k_step 30.0',
            '  k_comp 10000*k_step  # fast completion (boundary guard)',
            '  k_emit 1000*k_step  # rate-separated gene-stop emission',
            '  k_anti 0.145',
            '  k_tl 2.0',
            '  k_rnase 0.2',
            '  RNAPf_m 30',
            '  MOI 6',
            '  k1 0.0007',
            '  k2 0.05',
            '  k3 0.5',
            '  k4 0.0025',
            '  k5 0.05',
            '  k6 0.5',
            '  k7 0.00231',
            '  P1_tot 35.0',
            '  k8 0.01',
            '  k9 0.01',
            '  k10 0.002',
            '  k11 0.01',
            '  k12 0.001',
            '  k13 0.0001',
            '  P2_tot 140.0',
            '  k14 0.00025',
            '  k15 0.065',
            '  k16 0.6',
            '  k17 0.01',
            '  k18 0.01',
            '  k19 0.001',
            '  # OR site energies (kcal/mol); Arkin Table 1/2, Shea & Ackers 1985',
            '  dGR1 -11.7',
            '  dGR2 -10.1',
            '  dGR3 -10.1',
            '  dGC1 -10.8',
            '  dGC2 -10.8',
            '  dGC3 -12.1',
            '  dG12 -1.9',
            '  dG23 -2.0',
            '  dG_Rp -12.5',
            '  dG_RMp -11.5',
            '  NA 6.02214076e23',
            '  V_ref 1.66054e-15',
            '  molec_to_M 1/(NA*V_ref)  # = 1e-9 M/molecule',
            '  dimer_scale 0.5  # 1.0 clamp (dimer count) / 0.5 live Molecules dimer obs',
            '  R_gas 1.9872e-3',
            '  T_kelvin 310.15',
            '  RT R_gas*T_kelvin',
            '  # k_oc calibrated to Fig.2 peaks (P_R 0.013, P_RM 0.0063 OC/s; ratio 11)',
            '  kPR 0.0136741',
            '  kPRM1 0.0107315',
            '  kPRM2 0.00097559',
            '  # P_RE (CII activation) and P_L (Cro2/CI2 repression), Table 1',
            '  dG_RE_2 -9.9',
            '  dG_RE_3 -9.7',
            '  dG_RE_4 -21.5',
            '  koc_RE_2 4e-05',
            '  koc_RE_4 0.015',
            '  dG_L_2 -10.9',
            '  dG_L_3 -12.1',
            '  dG_L_4 -11.7',
            '  dG_L_5 -10.1',
            '  dG_L_6 -12.5',
            '  dG_L_7 -22.9',
            '  dG_L_8 -20.9',
            '  dG_L_9 -22.8',
            '  dG_L_10 -23.7',
            '  koc_L_6 0.011',
            '  k_fo_PR_tR1 1*k_step  # 50% terminate',
            '  k_fo_PL_tL1 4*k_step  # 80% terminate',
            'end parameters'],
 'mt_other': ['  N()',
              '  DNA()  # genome copy (seed at MOI); shared by all operons',
              '  mRNA_N()',
              '  mRNA_cI()',
              '  mRNA_cII()',
              '  mRNA_cIII()',
              '  mRNA_cro()',
              '  CI(d)',
              '  Cro(d)',
              '  CII(p)',
              '  CIII(p)',
              '  P1(s)',
              '  P2(s)',
              '  RNAPf()'],
 'seed': ['begin seed species',
          '  N() 0',
          '  mRNA_cro() 0',
          '  mRNA_cII() 0',
          '  mRNA_N() 0',
          '  mRNA_cIII() 0',
          '  mRNA_cI() 0',
          '  CI(d) 0',
          '  Cro(d) 0',
          '  CII(p) 0',
          '  CIII(p) 0',
          '  P1(s) P1_tot',
          '  P2(s) P2_tot',
          '  RNAPf() RNAPf_m',
          '  DNA() MOI',
          'end seed species'],
 'obs': ['begin observables',
         '  Molecules  Obs_CI2   CI(d!1).CI(d!1)',
         '  Molecules  Obs_Cro2  Cro(d!1).Cro(d!1)',
         '  Molecules  Obs_CII   CII(p)',
         '  Molecules  Obs_RNAP  RNAPf()',
         '  Molecules  Obs_N     N()',
         '  Species    CI2_dimer  CI(d!1).CI(d!1)',
         '  Species    Cro2_dimer Cro(d!1).Cro(d!1)',
         '  Molecules  CII_total CII()',
         '  Molecules  CIII_tot  CIII()',
         '  Molecules  CImon     CI(d)',
         '  Molecules  Crmon     Cro(d)',
         'end observables'],
 'fn_tail': ['  f_anti_PR() = k_anti*Obs_N', '  f_anti_PL() = k_anti*Obs_N'],
 'rules_extra': ['  # --- extra rules (translation / turnover / feedback) ---',
                 '  Rtl_Cro: mRNA_cro() -> mRNA_cro() + Cro(d) k_tl',
                 '  Rtl_CII: mRNA_cII() -> mRNA_cII() + CII(p) k_tl',
                 '  Rtl_N: mRNA_N() -> mRNA_N() + N() k_tl',
                 '  Rtl_CIII: mRNA_cIII() -> mRNA_cIII() + CIII(p) k_tl',
                 '  Rtl_CI: mRNA_cI() -> mRNA_cI() + CI(d) k_tl',
                 '  Rdeg_mRNA_cro: mRNA_cro() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_cII: mRNA_cII() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_N: mRNA_N() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_cIII: mRNA_cIII() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_cI: mRNA_cI() -> 0 k_rnase DeleteMolecules',
                 '  R_deg_CI:    CI(d) -> 0  k1',
                 '  R_dim_CI:    CI(d) + CI(d) <-> CI(d!1).CI(d!1)  k2, k3',
                 '  R_deg_Cro:   Cro(d) -> 0  k4',
                 '  R_dim_Cro:   Cro(d) + Cro(d) <-> Cro(d!1).Cro(d!1)  k5, k6',
                 '  R_deg_N:     N() -> 0  k7',
                 '  R_P1_bind_CII:   CII(p) + P1(s) <-> CII(p!1).P1(s!1)  k8, k9',
                 '  R_P1_deg_CII:    CII(p!1).P1(s!1) -> P1(s)  k10  DeleteMolecules',
                 '  R_P1_bind_CIII:  CIII(p) + P1(s) <-> CIII(p!1).P1(s!1)  k11, k12',
                 '  R_P1_deg_CIII:   CIII(p!1).P1(s!1) -> P1(s)  k13  DeleteMolecules',
                 '  R_P2_bind_CII:   CII(p) + P2(s) <-> CII(p!1).P2(s!1)  k14, k15',
                 '  R_P2_deg_CII:    CII(p!1).P2(s!1) -> P2(s)  k16  DeleteMolecules',
                 '  R_P2_bind_CIII:  CIII(p) + P2(s) <-> CIII(p!1).P2(s!1)  k17, k18',
                 '  R_P2_deg_CIII:   CIII(p!1).P2(s!1) -> P2(s)  k19  DeleteMolecules'],
 'rules_growth': [],
 'actions': ['begin actions', '  writeXML()', 'end actions']}

EXACT = {'header': ['# lambda_switch_arkin1998_fullcircuit_exact.bngl',
            '#',
            '# PAPER-EXACT variant of lambda_switch_arkin1998_fullcircuit.bngl (issue #6). '
            'Identical to',
            '# the decision-level full circuit EXCEPT it closes the two fidelity gaps that move '
            'the',
            '# Arkin, Ross & McAdams (1998) reported numbers:',
            '#',
            '#   (1) CELL GROWTH + DILUTION (Table 3): V(t)=(1+k0*t)*1e-15 L, k0=4.76e-4/s, volume',
            '#       doubling over the 35-min cell cycle. Network-free BNGL has no simulation-time',
            '#       variable (BNG2.pl aborts on `time` in a function), so V(t) is carried by a',
            '#       VOLUME-PROXY CLOCK species Vol(): a buffered Src() drives Src()->Src()+Vol() '
            'at',
            '#       k0*Vol0, so Obs_Vol/Vol0 = 1+k0*t = V(t)/V_ref = g(t). Growth dilution is '
            'then a',
            "#       first-order 'decay' X()->0 on every PHAGE species at the exact linear-growth",
            '#       specific rate mu(t)=k0/g(t)=k_grow/Obs_Vol (so a stable species halves '
            'exactly at',
            '#       volume doubling). Host/buffered pools (RNAP, P1, P2) and the non-replicating',
            '#       O-/P- genome DNA() are held at constant concentration (constant count) and '
            'are NOT',
            '#       diluted. This pulls the Fig-3a Cro2 plateau down from the constant-volume ~80 '
            'nM',
            "#       toward the paper's ~55 nM. (Concentration-space bimolecular rate constants "
            'are',
            '#       volume-independent, and fast dimer re-equilibration reproduces the extra '
            'dimer',
            '#       drop, so forward bimolecular rates are NOT separately rescaled by 1/V.)',
            '#',
            '#   (2) ANTITERMINATION SATURATION (Table 2): the nut sites are now a SLOW step with',
            '#       REVERSIBLE N loading, replacing the one-way functional antitermination. An '
            'RNAP',
            '#       that reaches nutR/nutL is intercepted into a paused state (at~n); from there '
            'it',
            "#       either escapes un-antiterminated at k23=5 nt/s (slow -- the paper's key "
            'dwell) or',
            '#       loads N at k24*[N] (k24=0.145) into at~m, which reverses at k25=0.1/s and '
            'escapes',
            '#       antiterminated at k26=30 nt/s. Per-pass antitermination is thus '
            '0.145N/(0.145N+5)',
            '#       -- ~6x stronger than the old 0.145N/(0.145N+30), because the escape it '
            'competes',
            '#       with is the slow nut step, not the fast generic 30 nt/s step. This restores '
            'the',
            "#       Fig-6a onset to MOI>3 (the old model's weaker per-pass antiterm put it at "
            '4->5).',
            '#       tR1 (50%) / tL1 (~80%) terminator fall-off fractions and free readthrough of '
            'the',
            '#       antiterminated (at~a) RNAP are already exact in the base model and are '
            'unchanged.',
            '#',
            '# Translation stays the geometric-burst competition (mean 10; deprioritized item #6). '
            'The',
            '# full per-nt elongation and Erlang cross-check remain out of scope for this variant.',
            '# Run exactly like the base model (writeXML -> NFsim/RuleMonkey via '
            'run_fullcircuit.py).',
            '#',
            '# --- base-model header follows ---',
            '# (was) lambda_switch_arkin1998_fullcircuit.bngl',
            '#',
            '# FULL lysis/lysogeny decision circuit of bacteriophage lambda, after',
            '#   Arkin, Ross & McAdams (1998), Genetics 149:1633-1648.',
            '#',
            '# This is the complete closed-loop, NETWORK-FREE reconstruction (run with NFsim or',
            '# RuleMonkey), the genetic-circuit companion to the curated non-genetic network in',
            '# lambda_switch_arkin1998.bngl (Table 3, R1-R5) and the Shea-Ackers promoter',
            '# activation in lambda_switch_arkin1998_promoters.bngl (Table 1). It couples:',
            '#',
            '#   TRANSCRIPTION (four operons P_R, P_L, P_RM, P_RE) as a state-increment ("~PLUS")',
            '#     RNAP-position model: one generic stepping rule per operon advances loc~? by one',
            '#     nt-equivalent; N-antitermination at nutR/nutL (unimolecular functional rate',
            '#     k_anti*N) and terminator fall-off at tR1 (~50%) / tL1 (~80%) compete with the',
            '#     step; gene stops emit mRNA. Initiation propensities are the Shea-Ackers open-',
            '#     complex rates A_PR()/A_PRM() (40-config O_R partition function, Table 1/2) and',
            '#     A_PRE()/A_PL() (Table 1), evaluated live from the current repressor levels.',
            '#   TRANSLATION as a geometric-burst competition per transcript (mean 10 proteins,',
            '#     Arkin Table 2 / assumption 8): mRNA_X -> mRNA_X + X at k_tl=2.0/s vs',
            '#     mRNA_X -> 0 at k_rnase=0.2/s.',
            '#   PROTEIN TURNOVER R1-R5 (Table 3): CI/Cro dimerization+degradation, N decay, and',
            '#     CII/CIII competitive proteolysis by two host proteases (P1=35, P2=140 nM) with',
            '#     CIII protection of CII -- verbatim from lambda_switch_arkin1998.bngl.',
            '#',
            '# The four promoters are read from the LIVE proteins the circuit produces, closing '
            'the',
            '# feedback loop: A_PR/A_PRM/A_PL <- CI2 & Cro2 dimers; A_PRE <- free CII; antiterm <- '
            'N.',
            '#',
            '# MOI (multiplicity of infection = phage genome copies) is the parameter MOI (default',
            '# 6, the Arkin Fig 3-5 value). Initiation is catalytic on a shared genome species',
            '# DNA() seeded at MOI: DNA() -> DNA() + RNAP(...) A_X(), so total initiation for',
            '# operon X is A_X()*MOI (each genome copy equilibrates with the shared free-repressor',
            '# / free-RNAP pools -- standard Shea-Ackers). MOI=1 reduces to a single genome.',
            '# Free RNAP (30 nM), ribosomes, and proteases are constant buffered pools (Arkin',
            '# modeling assumptions 3 & 6). Cell growth/dilution is not modeled (constant volume;',
            '# 1 molecule ~ 1 nM at V_ref=1.66054e-15 L, so molecule counts read as nM).',
            '#',
            '# NETWORK-FREE ENGINE NOTE (important): the promoter functional rates are driven by',
            '# MOLECULES-type observables of the dimers -- Obs_CI2/Obs_Cro2 = Molecules',
            '# CI(d!1).CI(d!1) / Cro(d!1).Cro(d!1) = 2x the dimer COUNT -- with dimer_scale=0.5 in',
            '# the partition functions to recover the dimer concentration. NFsim silently FREEZES '
            'a',
            '# functional rate that depends on a SPECIES-type observable (it refreshes such rates',
            '# only at output times, not on reaction events; RuleWorld/nfsim#86), so the live',
            '# repressor feedback MUST be read from Molecules obs. The Species readouts CI2_dimer '
            '/',
            '# Cro2_dimer are for plotting (clean dimer count) and to keep NFsim complex '
            'bookkeeping',
            '# (-cb) enabled; they never drive a rate.',
            '#',
            '# Lysogeny classifier (Arkin footnote 12, p.1639-1640): a cell is committed to '
            'lysogeny',
            '# when free-CII production activated P_RE and [CI2] > [Cro2] at the end of the 35-min',
            '# cell cycle. Run with the companion driver run_fullcircuit.py.',
            '#',
            '# Actions: writeXML only -- this is a network-free model. Generate XML with',
            '#   `bionetgen run -i lambda_switch_arkin1998_fullcircuit.bngl`',
            '# then simulate the XML with NFsim (needs -cb) or RuleMonkey; run_fullcircuit.py does',
            '# this via bngsim and reproduces Arkin Figs 3 and 6.',
            '#',
            '# Generated from models/lambda_switch_arkin1998/generator/ (plus_gen.py ~PLUS generator +',
            '# or_system.py / pre_pl.py Shea-Ackers rates + build_fullcircuit.py assembly).',
            ''],
 'params': ['begin parameters',
            '  k_step 30.0',
            '  k_comp 10000*k_step  # fast completion (boundary guard)',
            '  k_emit 1000*k_step  # rate-separated gene-stop emission',
            '  k_anti 0.145',
            '  k_tl 2.0',
            '  k_rnase 0.2',
            '  RNAPf_m 30',
            '  MOI 6',
            '  k1 0.0007',
            '  k2 0.05',
            '  k3 0.5',
            '  k4 0.0025',
            '  k5 0.05',
            '  k6 0.5',
            '  k7 0.00231',
            '  P1_tot 35.0',
            '  k8 0.01',
            '  k9 0.01',
            '  k10 0.002',
            '  k11 0.01',
            '  k12 0.001',
            '  k13 0.0001',
            '  P2_tot 140.0',
            '  k14 0.00025',
            '  k15 0.065',
            '  k16 0.6',
            '  k17 0.01',
            '  k18 0.01',
            '  k19 0.001',
            '  # OR site energies (kcal/mol); Arkin Table 1/2, Shea & Ackers 1985',
            '  dGR1 -11.7',
            '  dGR2 -10.1',
            '  dGR3 -10.1',
            '  dGC1 -10.8',
            '  dGC2 -10.8',
            '  dGC3 -12.1',
            '  dG12 -1.9',
            '  dG23 -2.0',
            '  dG_Rp -12.5',
            '  dG_RMp -11.5',
            '  NA 6.02214076e23',
            '  V_ref 1.66054e-15',
            '  molec_to_M 1/(NA*V_ref)  # = 1e-9 M/molecule',
            '  dimer_scale 0.5  # 1.0 clamp (dimer count) / 0.5 live Molecules dimer obs',
            '  R_gas 1.9872e-3',
            '  T_kelvin 310.15',
            '  RT R_gas*T_kelvin',
            '  # k_oc calibrated to Fig.2 peaks (P_R 0.013, P_RM 0.0063 OC/s; ratio 11)',
            '  kPR 0.0136741',
            '  kPRM1 0.0107315',
            '  kPRM2 0.00097559',
            '  # P_RE (CII activation) and P_L (Cro2/CI2 repression), Table 1',
            '  dG_RE_2 -9.9',
            '  dG_RE_3 -9.7',
            '  dG_RE_4 -21.5',
            '  koc_RE_2 4e-05',
            '  koc_RE_4 0.015',
            '  dG_L_2 -10.9',
            '  dG_L_3 -12.1',
            '  dG_L_4 -11.7',
            '  dG_L_5 -10.1',
            '  dG_L_6 -12.5',
            '  dG_L_7 -22.9',
            '  dG_L_8 -20.9',
            '  dG_L_9 -22.8',
            '  dG_L_10 -23.7',
            '  koc_L_6 0.011',
            '  k_fo_PR_tR1 1*k_step  # 50% terminate',
            '  k_fo_PL_tL1 4*k_step  # 80% terminate',
            '  # === issue #6 exact-variant additions ===',
            '  # cell growth / dilution (Arkin Table 3): V(t)=(1+k0*t)*1e-15 L, doubles in 35 min',
            '  k0 4.76e-4          # 1/2100 s; linear volume-growth rate constant',
            '  Vol0 1000           # volume-proxy clock seed (Obs_Vol/Vol0 = V(t)/V_ref = 1+k0*t)',
            '  k_grow k0*Vol0      # Src()->Src()+Vol() so d(Vol)/dt=k0*Vol0 -> Vol=Vol0*(1+k0*t)',
            '  # antitermination nut mechanism (Arkin Table 2): slow nut step + reversible N '
            'loading',
            "  k23 5.0             # un-antiterminated escape from nut (nt/s) -- the paper's slow "
            'dwell',
            '  k24 0.145           # N loading rate (== old k_anti); f_load = k24*Obs_N',
            '  k25 0.1             # N unloading rate (1/s)',
            '  k26 30.0            # antiterminated escape from nut (nt/s)',
            '  k_pause 1e5         # fast intercept: generic step must not skip the nut decision',
            'end parameters'],
 'mt_other': ['  N()',
              '  DNA()  # genome copy (seed at MOI); shared by all operons',
              '  mRNA_N()',
              '  mRNA_cI()',
              '  mRNA_cII()',
              '  mRNA_cIII()',
              '  mRNA_cro()',
              '  CI(d)',
              '  Cro(d)',
              '  CII(p)',
              '  CIII(p)',
              '  P1(s)',
              '  P2(s)',
              '  RNAPf()',
              '  Vol()   # volume-proxy clock: count/Vol0 = V(t)/V_ref',
              '  Src()   # buffered driver of the volume clock (constant, count 1)'],
 'seed': ['begin seed species',
          '  N() 0',
          '  mRNA_cro() 0',
          '  mRNA_cII() 0',
          '  mRNA_N() 0',
          '  mRNA_cIII() 0',
          '  mRNA_cI() 0',
          '  CI(d) 0',
          '  Cro(d) 0',
          '  CII(p) 0',
          '  CIII(p) 0',
          '  P1(s) P1_tot',
          '  P2(s) P2_tot',
          '  RNAPf() RNAPf_m',
          '  DNA() MOI',
          '  Vol() Vol0',
          '  Src() 1',
          'end seed species'],
 'obs': ['begin observables',
         '  Molecules  Obs_CI2   CI(d!1).CI(d!1)',
         '  Molecules  Obs_Cro2  Cro(d!1).Cro(d!1)',
         '  Molecules  Obs_CII   CII(p)',
         '  Molecules  Obs_RNAP  RNAPf()',
         '  Molecules  Obs_N     N()',
         '  Species    CI2_dimer  CI(d!1).CI(d!1)',
         '  Species    Cro2_dimer Cro(d!1).Cro(d!1)',
         '  Molecules  CII_total CII()',
         '  Molecules  CIII_tot  CIII()',
         '  Molecules  CImon     CI(d)',
         '  Molecules  Crmon     Cro(d)',
         '  Molecules  Obs_Vol    Vol()',
         'end observables'],
 'fn_tail': ['  f_load() = k24*Obs_N       # reversible N-loading propensity at the nut (both '
             'operons)',
             '  mu_dil() = k_grow/Obs_Vol  # linear-growth dilution specific rate = k0/g(t)'],
 'rules_extra': ['  # --- extra rules (translation / turnover / feedback) ---',
                 '  Rtl_Cro: mRNA_cro() -> mRNA_cro() + Cro(d) k_tl',
                 '  Rtl_CII: mRNA_cII() -> mRNA_cII() + CII(p) k_tl',
                 '  Rtl_N: mRNA_N() -> mRNA_N() + N() k_tl',
                 '  Rtl_CIII: mRNA_cIII() -> mRNA_cIII() + CIII(p) k_tl',
                 '  Rtl_CI: mRNA_cI() -> mRNA_cI() + CI(d) k_tl',
                 '  Rdeg_mRNA_cro: mRNA_cro() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_cII: mRNA_cII() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_N: mRNA_N() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_cIII: mRNA_cIII() -> 0 k_rnase DeleteMolecules',
                 '  Rdeg_mRNA_cI: mRNA_cI() -> 0 k_rnase DeleteMolecules',
                 '  R_deg_CI:    CI(d) -> 0  k1',
                 '  R_dim_CI:    CI(d) + CI(d) <-> CI(d!1).CI(d!1)  k2, k3',
                 '  R_deg_Cro:   Cro(d) -> 0  k4',
                 '  R_dim_Cro:   Cro(d) + Cro(d) <-> Cro(d!1).Cro(d!1)  k5, k6',
                 '  R_deg_N:     N() -> 0  k7',
                 '  R_P1_bind_CII:   CII(p) + P1(s) <-> CII(p!1).P1(s!1)  k8, k9',
                 '  R_P1_deg_CII:    CII(p!1).P1(s!1) -> P1(s)  k10  DeleteMolecules',
                 '  R_P1_bind_CIII:  CIII(p) + P1(s) <-> CIII(p!1).P1(s!1)  k11, k12',
                 '  R_P1_deg_CIII:   CIII(p!1).P1(s!1) -> P1(s)  k13  DeleteMolecules',
                 '  R_P2_bind_CII:   CII(p) + P2(s) <-> CII(p!1).P2(s!1)  k14, k15',
                 '  R_P2_deg_CII:    CII(p!1).P2(s!1) -> P2(s)  k16  DeleteMolecules',
                 '  R_P2_bind_CIII:  CIII(p) + P2(s) <-> CIII(p!1).P2(s!1)  k17, k18',
                 '  R_P2_deg_CIII:   CIII(p!1).P2(s!1) -> P2(s)  k19  DeleteMolecules'],
 'rules_growth': ['  # === issue #6 exact-variant reactions: growth clock + dilution ===',
                  '  # volume-proxy clock: Vol grows linearly so Obs_Vol/Vol0 = 1+k0*t = '
                  'V(t)/V_ref',
                  '  Rgrow: Src() -> Src() + Vol() k_grow',
                  '  # first-order growth dilution on every phage species at mu(t)=k0/g(t) (host '
                  'pools &',
                  '  # the non-replicating genome are constant-concentration and are NOT diluted)',
                  '  Rdil_mRNA_cro:  mRNA_cro()  -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_mRNA_cII:  mRNA_cII()  -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_mRNA_N:    mRNA_N()    -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_mRNA_cIII: mRNA_cIII() -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_mRNA_cI:   mRNA_cI()   -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_N:         N()         -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_CImon:     CI(d)       -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_CI2:       CI(d!1).CI(d!1)   -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_Crmon:     Cro(d)      -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_Cro2:      Cro(d!1).Cro(d!1) -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_CII:       CII(p)      -> 0 mu_dil() DeleteMolecules',
                  '  Rdil_CIII:      CIII(p)     -> 0 mu_dil() DeleteMolecules'],
 'actions': ['begin actions', '  writeXML()', 'end actions']}

